
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: "no"

  adminer:
    container_name: adminer_container
    image: adminer
    restart: "no"
    ports:
      - "8081:8080"
    volumes:
      - adminer:/var/lib/adminer
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  adminer: